create table tb_master_user
(
    id           bigint generated by default as identity
        primary key,
    created_date timestamp(6) not null,
    email        varchar(255),
    password     varchar(255),
    role         smallint
        constraint tb_master_user_role_check
            check ((role >= 0) AND (role <= 1)),
    updated_date timestamp(6) not null,
    username     varchar(255)
);

alter table public.tb_master_user
    owner to meterbill_user;

